### ISSUE TITLE
节拍器能不能增加计时功能呢？

### ISSUE THREAD

**Issue by ditele1** [LaoQi/SimpleBeat#4]
这个节拍器简单易用，我想用来跑步用，能不能设定时间 时间到了自动暂停。

**Comment by LaoQi** [comment]
可以是可以，我有空加上去吧。不过居然是用来跑步的，按节奏跑么？

**Comment by ditele1** [comment]
对的对的，按节奏慢跑可以边看电视边跑，一点也不累又能达到锻炼目的。

**Comment by LaoQi** [comment]
新的release里增加了定时器功能，因为调整了签名，需要删除原有的应用再安装
